export const FETCH_BOOK_START = "FETCH_BOOK_START";
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_BOOK_ERROR = "FETCH_BOOK_ERROR";

export const UPDATE_BOOK = "UPDATE_BOOK";

export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";

export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_START = "DELETE_BOOK_START";